-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language exp.

module Syntax.Exp.Abs where

import Prelude (Double, Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Exp
    = BTrue
    | Single TSingle
    | Var Ident
    | DVal Double
    | IVal Integer
    | BFalse
    | Rand
    | Pair Exp Exp
    | Next Exp
    | Prev Environment Exp
    | PrevE Exp
    | PrevI Exp
    | Box Environment Exp
    | BoxI Exp
    | Unbox Exp
    | Force Exp
    | In Exp
    | Out Exp
    | Fst Exp
    | Snd Exp
    | InL Exp
    | InR Exp
    | App Exp Exp
    | LApp Exp TLApp Exp
    | Min Exp
    | Pow Exp Exp
    | Mul Exp Exp
    | Div Exp Exp
    | Mod Exp Exp
    | Add Exp Exp
    | Sub Exp Exp
    | Eq Exp Exp
    | Lt Exp Exp
    | Gt Exp Exp
    | Leq Exp TLeq Exp
    | Geq Exp TGeq Exp
    | Not TNot Exp
    | And Exp Conj Exp
    | Or Exp Disj Exp
    | Norm Exp
    | Ite Exp Exp Exp
    | Match Exp Ident TMatch Exp Ident TMatch Exp
    | Rec Ident Exp
    | LetIn Environment Exp
    | Abstr Lam Ident Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Assignment = Assign Ident TSub Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Environment = Env [Assignment]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype Lam = Lam String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype Conj = Conj String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype Disj = Disj String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TNot = TNot String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TLeq = TLeq String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TGeq = TGeq String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TLApp = TLApp String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TSub = TSub String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TMatch = TMatch String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TSingle = TSingle String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

