-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Syntax.

module Syntax.Exp.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Syntax.Exp.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Syntax.Exp.Abs.Ident where
  prt _ (Syntax.Exp.Abs.Ident i) = doc $ showString i
instance Print Syntax.Exp.Abs.Lam where
  prt _ (Syntax.Exp.Abs.Lam i) = doc $ showString i
instance Print Syntax.Exp.Abs.Conj where
  prt _ (Syntax.Exp.Abs.Conj i) = doc $ showString i
instance Print Syntax.Exp.Abs.Disj where
  prt _ (Syntax.Exp.Abs.Disj i) = doc $ showString i
instance Print Syntax.Exp.Abs.TNot where
  prt _ (Syntax.Exp.Abs.TNot i) = doc $ showString i
instance Print Syntax.Exp.Abs.TLeq where
  prt _ (Syntax.Exp.Abs.TLeq i) = doc $ showString i
instance Print Syntax.Exp.Abs.TGeq where
  prt _ (Syntax.Exp.Abs.TGeq i) = doc $ showString i
instance Print Syntax.Exp.Abs.TLApp where
  prt _ (Syntax.Exp.Abs.TLApp i) = doc $ showString i
instance Print Syntax.Exp.Abs.TSub where
  prt _ (Syntax.Exp.Abs.TSub i) = doc $ showString i
instance Print Syntax.Exp.Abs.TMatch where
  prt _ (Syntax.Exp.Abs.TMatch i) = doc $ showString i
instance Print Syntax.Exp.Abs.TSingle where
  prt _ (Syntax.Exp.Abs.TSingle i) = doc $ showString i
instance Print Syntax.Exp.Abs.Exp where
  prt i = \case
    Syntax.Exp.Abs.BTrue -> prPrec i 14 (concatD [doc (showString "true")])
    Syntax.Exp.Abs.Single tsingle -> prPrec i 14 (concatD [prt 0 tsingle])
    Syntax.Exp.Abs.Var id_ -> prPrec i 14 (concatD [prt 0 id_])
    Syntax.Exp.Abs.DVal d -> prPrec i 14 (concatD [prt 0 d])
    Syntax.Exp.Abs.IVal n -> prPrec i 14 (concatD [prt 0 n])
    Syntax.Exp.Abs.BFalse -> prPrec i 14 (concatD [doc (showString "false")])
    Syntax.Exp.Abs.Rand -> prPrec i 14 (concatD [doc (showString "rand")])
    Syntax.Exp.Abs.Pair exp1 exp2 -> prPrec i 13 (concatD [doc (showString "("), prt 13 exp1, doc (showString ","), prt 14 exp2, doc (showString ")")])
    Syntax.Exp.Abs.Next exp -> prPrec i 13 (concatD [doc (showString "next"), prt 14 exp])
    Syntax.Exp.Abs.Prev environment exp -> prPrec i 13 (concatD [doc (showString "prev"), doc (showString "{"), prt 0 environment, doc (showString "}"), doc (showString "."), prt 13 exp])
    Syntax.Exp.Abs.PrevE exp -> prPrec i 13 (concatD [doc (showString "prev"), prt 14 exp])
    Syntax.Exp.Abs.PrevI exp -> prPrec i 13 (concatD [doc (showString "prevI"), prt 14 exp])
    Syntax.Exp.Abs.Box environment exp -> prPrec i 13 (concatD [doc (showString "box"), doc (showString "{"), prt 0 environment, doc (showString "}"), doc (showString "."), prt 13 exp])
    Syntax.Exp.Abs.BoxI exp -> prPrec i 13 (concatD [doc (showString "boxI"), prt 14 exp])
    Syntax.Exp.Abs.Unbox exp -> prPrec i 13 (concatD [doc (showString "unbox"), prt 14 exp])
    Syntax.Exp.Abs.Force exp -> prPrec i 13 (concatD [doc (showString "force"), prt 14 exp])
    Syntax.Exp.Abs.In exp -> prPrec i 12 (concatD [doc (showString "in"), prt 13 exp])
    Syntax.Exp.Abs.Out exp -> prPrec i 12 (concatD [doc (showString "out"), prt 13 exp])
    Syntax.Exp.Abs.Fst exp -> prPrec i 12 (concatD [doc (showString "fst"), prt 13 exp])
    Syntax.Exp.Abs.Snd exp -> prPrec i 12 (concatD [doc (showString "snd"), prt 13 exp])
    Syntax.Exp.Abs.InL exp -> prPrec i 12 (concatD [doc (showString "inL"), prt 13 exp])
    Syntax.Exp.Abs.InR exp -> prPrec i 12 (concatD [doc (showString "inR"), prt 13 exp])
    Syntax.Exp.Abs.App exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, prt 12 exp2])
    Syntax.Exp.Abs.LApp exp1 tlapp exp2 -> prPrec i 11 (concatD [prt 11 exp1, prt 0 tlapp, prt 12 exp2])
    Syntax.Exp.Abs.Min exp -> prPrec i 10 (concatD [doc (showString "-"), prt 11 exp])
    Syntax.Exp.Abs.Pow exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "^"), prt 10 exp2])
    Syntax.Exp.Abs.Mul exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "*"), prt 9 exp2])
    Syntax.Exp.Abs.Div exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "/"), prt 9 exp2])
    Syntax.Exp.Abs.Mod exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "%"), prt 9 exp2])
    Syntax.Exp.Abs.Add exp1 exp2 -> prPrec i 7 (concatD [prt 7 exp1, doc (showString "+"), prt 8 exp2])
    Syntax.Exp.Abs.Sub exp1 exp2 -> prPrec i 7 (concatD [prt 7 exp1, doc (showString "-"), prt 8 exp2])
    Syntax.Exp.Abs.Eq exp1 exp2 -> prPrec i 6 (concatD [prt 6 exp1, doc (showString "="), prt 7 exp2])
    Syntax.Exp.Abs.Lt exp1 exp2 -> prPrec i 6 (concatD [prt 6 exp1, doc (showString "<"), prt 7 exp2])
    Syntax.Exp.Abs.Gt exp1 exp2 -> prPrec i 6 (concatD [prt 6 exp1, doc (showString ">"), prt 7 exp2])
    Syntax.Exp.Abs.Leq exp1 tleq exp2 -> prPrec i 6 (concatD [prt 6 exp1, prt 0 tleq, prt 7 exp2])
    Syntax.Exp.Abs.Geq exp1 tgeq exp2 -> prPrec i 6 (concatD [prt 6 exp1, prt 0 tgeq, prt 7 exp2])
    Syntax.Exp.Abs.Not tnot exp -> prPrec i 5 (concatD [prt 0 tnot, prt 6 exp])
    Syntax.Exp.Abs.And exp1 conj exp2 -> prPrec i 4 (concatD [prt 4 exp1, prt 0 conj, prt 5 exp2])
    Syntax.Exp.Abs.Or exp1 disj exp2 -> prPrec i 4 (concatD [prt 4 exp1, prt 0 disj, prt 5 exp2])
    Syntax.Exp.Abs.Norm exp -> prPrec i 3 (concatD [doc (showString "normal"), prt 4 exp])
    Syntax.Exp.Abs.Ite exp1 exp2 exp3 -> prPrec i 2 (concatD [doc (showString "if"), prt 2 exp1, doc (showString "then"), prt 3 exp2, doc (showString "else"), prt 3 exp3])
    Syntax.Exp.Abs.Match exp1 id_1 tmatch1 exp2 id_2 tmatch2 exp3 -> prPrec i 1 (concatD [doc (showString "match"), prt 1 exp1, doc (showString "{"), doc (showString "inL"), prt 0 id_1, prt 0 tmatch1, prt 2 exp2, doc (showString ";"), doc (showString "inR"), prt 0 id_2, prt 0 tmatch2, prt 2 exp3, doc (showString "}")])
    Syntax.Exp.Abs.Rec id_ exp -> prPrec i 0 (concatD [doc (showString "fix"), prt 0 id_, doc (showString "."), prt 1 exp])
    Syntax.Exp.Abs.LetIn environment exp -> prPrec i 0 (concatD [doc (showString "let"), prt 0 environment, doc (showString "in:"), prt 1 exp])
    Syntax.Exp.Abs.Abstr lam id_ exp -> prPrec i 0 (concatD [prt 0 lam, prt 0 id_, doc (showString "."), prt 0 exp])

instance Print [Syntax.Exp.Abs.Exp] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Syntax.Exp.Abs.Environment where
  prt i = \case
    Syntax.Exp.Abs.Env assignments -> prPrec i 0 (concatD [prt 0 assignments])

instance Print Syntax.Exp.Abs.Assignment where
  prt i = \case
    Syntax.Exp.Abs.Assign id_ tsub exp -> prPrec i 0 (concatD [prt 0 id_, prt 0 tsub, prt 0 exp])

instance Print [Syntax.Exp.Abs.Assignment] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]
