-- File generated by the BNF Converter (bnfc 2.9.6.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module Syntax.Exp.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Syntax.Exp.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Syntax.Exp.Abs.Ident -> Result
transIdent x = case x of
  Syntax.Exp.Abs.Ident string -> failure x

transLam :: Syntax.Exp.Abs.Lam -> Result
transLam x = case x of
  Syntax.Exp.Abs.Lam string -> failure x

transConj :: Syntax.Exp.Abs.Conj -> Result
transConj x = case x of
  Syntax.Exp.Abs.Conj string -> failure x

transDisj :: Syntax.Exp.Abs.Disj -> Result
transDisj x = case x of
  Syntax.Exp.Abs.Disj string -> failure x

transTNot :: Syntax.Exp.Abs.TNot -> Result
transTNot x = case x of
  Syntax.Exp.Abs.TNot string -> failure x

transTLeq :: Syntax.Exp.Abs.TLeq -> Result
transTLeq x = case x of
  Syntax.Exp.Abs.TLeq string -> failure x

transTGeq :: Syntax.Exp.Abs.TGeq -> Result
transTGeq x = case x of
  Syntax.Exp.Abs.TGeq string -> failure x

transTLApp :: Syntax.Exp.Abs.TLApp -> Result
transTLApp x = case x of
  Syntax.Exp.Abs.TLApp string -> failure x

transTSub :: Syntax.Exp.Abs.TSub -> Result
transTSub x = case x of
  Syntax.Exp.Abs.TSub string -> failure x

transTMatch :: Syntax.Exp.Abs.TMatch -> Result
transTMatch x = case x of
  Syntax.Exp.Abs.TMatch string -> failure x

transTSingle :: Syntax.Exp.Abs.TSingle -> Result
transTSingle x = case x of
  Syntax.Exp.Abs.TSingle string -> failure x

transBConst :: Syntax.Exp.Abs.BConst -> Result
transBConst x = case x of
  Syntax.Exp.Abs.BTrue -> failure x
  Syntax.Exp.Abs.BFalse -> failure x

transExp :: Syntax.Exp.Abs.Exp -> Result
transExp x = case x of
  Syntax.Exp.Abs.Single tsingle -> failure x
  Syntax.Exp.Abs.Var ident -> failure x
  Syntax.Exp.Abs.DVal double -> failure x
  Syntax.Exp.Abs.IVal integer -> failure x
  Syntax.Exp.Abs.BVal bconst -> failure x
  Syntax.Exp.Abs.EList lst -> failure x
  Syntax.Exp.Abs.Pair exp1 exp2 -> failure x
  Syntax.Exp.Abs.Next exp -> failure x
  Syntax.Exp.Abs.Prev environment exp -> failure x
  Syntax.Exp.Abs.PrevE exp -> failure x
  Syntax.Exp.Abs.PrevI exp -> failure x
  Syntax.Exp.Abs.Box environment exp -> failure x
  Syntax.Exp.Abs.BoxI exp -> failure x
  Syntax.Exp.Abs.Unbox exp -> failure x
  Syntax.Exp.Abs.Force exp -> failure x
  Syntax.Exp.Abs.Rand -> failure x
  Syntax.Exp.Abs.ListIndex exp1 exp2 -> failure x
  Syntax.Exp.Abs.In exp -> failure x
  Syntax.Exp.Abs.Out exp -> failure x
  Syntax.Exp.Abs.Fst exp -> failure x
  Syntax.Exp.Abs.Snd exp -> failure x
  Syntax.Exp.Abs.InL exp -> failure x
  Syntax.Exp.Abs.InR exp -> failure x
  Syntax.Exp.Abs.ListHead exp -> failure x
  Syntax.Exp.Abs.ListTail exp -> failure x
  Syntax.Exp.Abs.ListNull exp -> failure x
  Syntax.Exp.Abs.ListLength exp -> failure x
  Syntax.Exp.Abs.ListFold exp1 exp2 exp3 -> failure x
  Syntax.Exp.Abs.ListMap exp1 exp2 -> failure x
  Syntax.Exp.Abs.ListElem exp1 exp2 -> failure x
  Syntax.Exp.Abs.ListTake exp1 exp2 -> failure x
  Syntax.Exp.Abs.ListDrop exp1 exp2 -> failure x
  Syntax.Exp.Abs.App exp1 exp2 -> failure x
  Syntax.Exp.Abs.LApp exp1 tlapp exp2 -> failure x
  Syntax.Exp.Abs.ListCons exp1 exp2 -> failure x
  Syntax.Exp.Abs.ListAppend exp1 exp2 -> failure x
  Syntax.Exp.Abs.Min exp -> failure x
  Syntax.Exp.Abs.Pow exp1 exp2 -> failure x
  Syntax.Exp.Abs.Mul exp1 exp2 -> failure x
  Syntax.Exp.Abs.Div exp1 exp2 -> failure x
  Syntax.Exp.Abs.Mod exp1 exp2 -> failure x
  Syntax.Exp.Abs.Add exp1 exp2 -> failure x
  Syntax.Exp.Abs.Sub exp1 exp2 -> failure x
  Syntax.Exp.Abs.Eq exp1 exp2 -> failure x
  Syntax.Exp.Abs.Lt exp1 exp2 -> failure x
  Syntax.Exp.Abs.Gt exp1 exp2 -> failure x
  Syntax.Exp.Abs.Leq exp1 tleq exp2 -> failure x
  Syntax.Exp.Abs.Geq exp1 tgeq exp2 -> failure x
  Syntax.Exp.Abs.Not tnot exp -> failure x
  Syntax.Exp.Abs.And exp1 conj exp2 -> failure x
  Syntax.Exp.Abs.Or exp1 disj exp2 -> failure x
  Syntax.Exp.Abs.Norm exp -> failure x
  Syntax.Exp.Abs.Ite exp1 exp2 exp3 -> failure x
  Syntax.Exp.Abs.Match exp1 ident1 tmatch1 exp2 ident2 tmatch2 exp3 -> failure x
  Syntax.Exp.Abs.Abstr lam ident exp -> failure x
  Syntax.Exp.Abs.Rec ident exp -> failure x

transLst :: Syntax.Exp.Abs.Lst -> Result
transLst x = case x of
  Syntax.Exp.Abs.List exps -> failure x

transPrg :: Syntax.Exp.Abs.Prg -> Result
transPrg x = case x of
  Syntax.Exp.Abs.DefProg environment exp -> failure x
  Syntax.Exp.Abs.Prog exp -> failure x

transEnvironment :: Syntax.Exp.Abs.Environment -> Result
transEnvironment x = case x of
  Syntax.Exp.Abs.Env assignments -> failure x

transAssignment :: Syntax.Exp.Abs.Assignment -> Result
transAssignment x = case x of
  Syntax.Exp.Abs.Assign ident tsub exp -> failure x
