-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.5).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module TypeSyntax.RawTypes.Par
  ( happyError
  , myLexer
  , pEnvironment
  , pExp
  , pPrg
  ) where

import Prelude

import qualified TypeSyntax.RawTypes.Abs
import TypeSyntax.RawTypes.Lex

}

%name pEnvironment Environment
%name pExp Exp
%name pPrg Prg
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '('       { PT _ (TS _ 1)       }
  ')'       { PT _ (TS _ 2)       }
  '+'       { PT _ (TS _ 3)       }
  '.'       { PT _ (TS _ 4)       }
  'bool'    { PT _ (TS _ 5)       }
  'real'    { PT _ (TS _ 6)       }
  'x'       { PT _ (TS _ 7)       }
  L_Ident   { PT _ (TV $$)        }
  L_TLater  { PT _ (T_TLater $$)  }
  L_TBox    { PT _ (T_TBox $$)    }
  L_TMu     { PT _ (T_TMu $$)     }
  L_TRarrow { PT _ (T_TRarrow $$) }
  L_TSingle { PT _ (T_TSingle $$) }

%%

Ident :: { TypeSyntax.RawTypes.Abs.Ident }
Ident  : L_Ident { TypeSyntax.RawTypes.Abs.Ident $1 }

TLater :: { TypeSyntax.RawTypes.Abs.TLater }
TLater  : L_TLater { TypeSyntax.RawTypes.Abs.TLater $1 }

TBox :: { TypeSyntax.RawTypes.Abs.TBox }
TBox  : L_TBox { TypeSyntax.RawTypes.Abs.TBox $1 }

TMu :: { TypeSyntax.RawTypes.Abs.TMu }
TMu  : L_TMu { TypeSyntax.RawTypes.Abs.TMu $1 }

TRarrow :: { TypeSyntax.RawTypes.Abs.TRarrow }
TRarrow  : L_TRarrow { TypeSyntax.RawTypes.Abs.TRarrow $1 }

TSingle :: { TypeSyntax.RawTypes.Abs.TSingle }
TSingle  : L_TSingle { TypeSyntax.RawTypes.Abs.TSingle $1 }

Base :: { TypeSyntax.RawTypes.Abs.Base }
Base
  : 'bool' { TypeSyntax.RawTypes.Abs.Bool }
  | 'real' { TypeSyntax.RawTypes.Abs.Real }
  | Ident { TypeSyntax.RawTypes.Abs.Var $1 }

Ty10 :: { TypeSyntax.RawTypes.Abs.Ty }
Ty10 : Base { TypeSyntax.RawTypes.Abs.Leaf $1 } | '(' Ty ')' { $2 }

Ty9 :: { TypeSyntax.RawTypes.Abs.Ty }
Ty9
  : Ty9 'x' Ty10 { TypeSyntax.RawTypes.Abs.Prod $1 $3 } | Ty10 { $1 }

Ty8 :: { TypeSyntax.RawTypes.Abs.Ty }
Ty8
  : Ty8 '+' Ty9 { TypeSyntax.RawTypes.Abs.Coprod $1 $3 } | Ty9 { $1 }

Ty7 :: { TypeSyntax.RawTypes.Abs.Ty }
Ty7
  : Ty7 TRarrow Ty8 { TypeSyntax.RawTypes.Abs.Func $1 $2 $3 }
  | Ty8 { $1 }

Ty6 :: { TypeSyntax.RawTypes.Abs.Ty }
Ty6
  : TMu Ident '.' Ty7 { TypeSyntax.RawTypes.Abs.TyVar $1 $2 $4 }
  | Ty7 { $1 }

Ty5 :: { TypeSyntax.RawTypes.Abs.Ty }
Ty5
  : TLater Ty6 { TypeSyntax.RawTypes.Abs.TyLater $1 $2 }
  | TBox Ty6 { TypeSyntax.RawTypes.Abs.TyBox $1 $2 }
  | Ty6 { $1 }

Ty :: { TypeSyntax.RawTypes.Abs.Ty }
Ty : Ty1 { $1 }

Ty1 :: { TypeSyntax.RawTypes.Abs.Ty }
Ty1 : Ty2 { $1 }

Ty2 :: { TypeSyntax.RawTypes.Abs.Ty }
Ty2 : Ty3 { $1 }

Ty3 :: { TypeSyntax.RawTypes.Abs.Ty }
Ty3 : Ty4 { $1 }

Ty4 :: { TypeSyntax.RawTypes.Abs.Ty }
Ty4 : Ty5 { $1 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

