-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module TypeSyntax.RawTypes.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified TypeSyntax.RawTypes.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: TypeSyntax.RawTypes.Abs.Ident -> Result
transIdent x = case x of
  TypeSyntax.RawTypes.Abs.Ident string -> failure x

transTLater :: TypeSyntax.RawTypes.Abs.TLater -> Result
transTLater x = case x of
  TypeSyntax.RawTypes.Abs.TLater string -> failure x

transTBox :: TypeSyntax.RawTypes.Abs.TBox -> Result
transTBox x = case x of
  TypeSyntax.RawTypes.Abs.TBox string -> failure x

transTMu :: TypeSyntax.RawTypes.Abs.TMu -> Result
transTMu x = case x of
  TypeSyntax.RawTypes.Abs.TMu string -> failure x

transTRarrow :: TypeSyntax.RawTypes.Abs.TRarrow -> Result
transTRarrow x = case x of
  TypeSyntax.RawTypes.Abs.TRarrow string -> failure x

transTSingle :: TypeSyntax.RawTypes.Abs.TSingle -> Result
transTSingle x = case x of
  TypeSyntax.RawTypes.Abs.TSingle string -> failure x

transBase :: TypeSyntax.RawTypes.Abs.Base -> Result
transBase x = case x of
  TypeSyntax.RawTypes.Abs.Bool -> failure x
  TypeSyntax.RawTypes.Abs.Real -> failure x
  TypeSyntax.RawTypes.Abs.Var ident -> failure x

transTy :: TypeSyntax.RawTypes.Abs.Ty -> Result
transTy x = case x of
  TypeSyntax.RawTypes.Abs.Leaf base -> failure x
  TypeSyntax.RawTypes.Abs.Prod ty1 ty2 -> failure x
  TypeSyntax.RawTypes.Abs.Coprod ty1 ty2 -> failure x
  TypeSyntax.RawTypes.Abs.Func ty1 trarrow ty2 -> failure x
  TypeSyntax.RawTypes.Abs.TyVar tmu ident ty -> failure x
  TypeSyntax.RawTypes.Abs.TyLater tlater ty -> failure x
  TypeSyntax.RawTypes.Abs.TyBox tbox ty -> failure x
