-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language types.

module Syntax.Types.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Base = Bool | Real | Var Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Ty
    = Leaf Base
    | Prod Ty Ty
    | Coprod Ty Ty
    | Func Ty TRarrow Ty
    | TyLater TLater Ty
    | TyBox TBox Ty
    | TyVar TMu Ident Ty
    | TyForall TForall Ident Ty
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TForall = TForall String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TLater = TLater String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TBox = TBox String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TMu = TMu String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TRarrow = TRarrow String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TSingle = TSingle String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

