-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.5).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module Syntax.Types.Par
  ( happyError
  , myLexer
  , pTy
  ) where

import Prelude

import qualified Syntax.Types.Abs
import Syntax.Types.Lex

}

%name pTy Ty
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '('       { PT _ (TS _ 1)       }
  ')'       { PT _ (TS _ 2)       }
  '+'       { PT _ (TS _ 3)       }
  '.'       { PT _ (TS _ 4)       }
  'bool'    { PT _ (TS _ 5)       }
  'real'    { PT _ (TS _ 6)       }
  'x'       { PT _ (TS _ 7)       }
  L_Ident   { PT _ (TV $$)        }
  L_TForall { PT _ (T_TForall $$) }
  L_TLater  { PT _ (T_TLater $$)  }
  L_TBox    { PT _ (T_TBox $$)    }
  L_TMu     { PT _ (T_TMu $$)     }
  L_TRarrow { PT _ (T_TRarrow $$) }
  L_TSingle { PT _ (T_TSingle $$) }

%%

Ident :: { Syntax.Types.Abs.Ident }
Ident  : L_Ident { Syntax.Types.Abs.Ident $1 }

TForall :: { Syntax.Types.Abs.TForall }
TForall  : L_TForall { Syntax.Types.Abs.TForall $1 }

TLater :: { Syntax.Types.Abs.TLater }
TLater  : L_TLater { Syntax.Types.Abs.TLater $1 }

TBox :: { Syntax.Types.Abs.TBox }
TBox  : L_TBox { Syntax.Types.Abs.TBox $1 }

TMu :: { Syntax.Types.Abs.TMu }
TMu  : L_TMu { Syntax.Types.Abs.TMu $1 }

TRarrow :: { Syntax.Types.Abs.TRarrow }
TRarrow  : L_TRarrow { Syntax.Types.Abs.TRarrow $1 }

TSingle :: { Syntax.Types.Abs.TSingle }
TSingle  : L_TSingle { Syntax.Types.Abs.TSingle $1 }

Ty10 :: { Syntax.Types.Abs.Ty }
Ty10
  : TSingle { Syntax.Types.Abs.Single $1 }
  | 'bool' { Syntax.Types.Abs.Bool }
  | 'real' { Syntax.Types.Abs.Real }
  | Ident { Syntax.Types.Abs.Var $1 }
  | '(' Ty ')' { $2 }

Ty9 :: { Syntax.Types.Abs.Ty }
Ty9 : Ty9 'x' Ty10 { Syntax.Types.Abs.Prod $1 $3 } | Ty10 { $1 }

Ty8 :: { Syntax.Types.Abs.Ty }
Ty8 : Ty8 '+' Ty9 { Syntax.Types.Abs.Coprod $1 $3 } | Ty9 { $1 }

Ty7 :: { Syntax.Types.Abs.Ty }
Ty7
  : Ty7 TRarrow Ty8 { Syntax.Types.Abs.Func $1 $2 $3 } | Ty8 { $1 }

Ty5 :: { Syntax.Types.Abs.Ty }
Ty5
  : TLater Ty6 { Syntax.Types.Abs.TyLater $1 $2 }
  | TBox Ty6 { Syntax.Types.Abs.TyBox $1 $2 }
  | Ty6 { $1 }

Ty4 :: { Syntax.Types.Abs.Ty }
Ty4
  : TMu Ident '.' Ty5 { Syntax.Types.Abs.TyVar $1 $2 $4 }
  | TForall Ident '.' Ty5 { Syntax.Types.Abs.TyForall $1 $2 $4 }
  | Ty5 { $1 }

Ty :: { Syntax.Types.Abs.Ty }
Ty : Ty1 { $1 }

Ty1 :: { Syntax.Types.Abs.Ty }
Ty1 : Ty2 { $1 }

Ty2 :: { Syntax.Types.Abs.Ty }
Ty2 : Ty3 { $1 }

Ty3 :: { Syntax.Types.Abs.Ty }
Ty3 : Ty4 { $1 }

Ty6 :: { Syntax.Types.Abs.Ty }
Ty6 : Ty7 { $1 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

