-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for Syntax.

module Syntax.Types.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Syntax.Types.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Syntax.Types.Abs.Ident where
  prt _ (Syntax.Types.Abs.Ident i) = doc $ showString i
instance Print Syntax.Types.Abs.TLater where
  prt _ (Syntax.Types.Abs.TLater i) = doc $ showString i
instance Print Syntax.Types.Abs.TBox where
  prt _ (Syntax.Types.Abs.TBox i) = doc $ showString i
instance Print Syntax.Types.Abs.TMu where
  prt _ (Syntax.Types.Abs.TMu i) = doc $ showString i
instance Print Syntax.Types.Abs.TRarrow where
  prt _ (Syntax.Types.Abs.TRarrow i) = doc $ showString i
instance Print Syntax.Types.Abs.TSingle where
  prt _ (Syntax.Types.Abs.TSingle i) = doc $ showString i
instance Print Syntax.Types.Abs.Base where
  prt i = \case
    Syntax.Types.Abs.Bool -> prPrec i 0 (concatD [doc (showString "bool")])
    Syntax.Types.Abs.Real -> prPrec i 0 (concatD [doc (showString "real")])
    Syntax.Types.Abs.Var id_ -> prPrec i 0 (concatD [prt 0 id_])

instance Print Syntax.Types.Abs.Ty where
  prt i = \case
    Syntax.Types.Abs.Leaf base -> prPrec i 10 (concatD [prt 0 base])
    Syntax.Types.Abs.Prod ty1 ty2 -> prPrec i 9 (concatD [prt 9 ty1, doc (showString "x"), prt 10 ty2])
    Syntax.Types.Abs.Coprod ty1 ty2 -> prPrec i 8 (concatD [prt 8 ty1, doc (showString "+"), prt 9 ty2])
    Syntax.Types.Abs.Func ty1 trarrow ty2 -> prPrec i 7 (concatD [prt 7 ty1, prt 0 trarrow, prt 8 ty2])
    Syntax.Types.Abs.TyVar tmu id_ ty -> prPrec i 6 (concatD [prt 0 tmu, prt 0 id_, doc (showString "."), prt 7 ty])
    Syntax.Types.Abs.TyLater tlater ty -> prPrec i 5 (concatD [prt 0 tlater, prt 6 ty])
    Syntax.Types.Abs.TyBox tbox ty -> prPrec i 5 (concatD [prt 0 tbox, prt 6 ty])
