-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Syntax.Types.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Syntax.Types.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Syntax.Types.Abs.Ident -> Result
transIdent x = case x of
  Syntax.Types.Abs.Ident string -> failure x

transTForall :: Syntax.Types.Abs.TForall -> Result
transTForall x = case x of
  Syntax.Types.Abs.TForall string -> failure x

transTLater :: Syntax.Types.Abs.TLater -> Result
transTLater x = case x of
  Syntax.Types.Abs.TLater string -> failure x

transTBox :: Syntax.Types.Abs.TBox -> Result
transTBox x = case x of
  Syntax.Types.Abs.TBox string -> failure x

transTMu :: Syntax.Types.Abs.TMu -> Result
transTMu x = case x of
  Syntax.Types.Abs.TMu string -> failure x

transTRarrow :: Syntax.Types.Abs.TRarrow -> Result
transTRarrow x = case x of
  Syntax.Types.Abs.TRarrow string -> failure x

transTSingle :: Syntax.Types.Abs.TSingle -> Result
transTSingle x = case x of
  Syntax.Types.Abs.TSingle string -> failure x

transBase :: Syntax.Types.Abs.Base -> Result
transBase x = case x of
  Syntax.Types.Abs.Bool -> failure x
  Syntax.Types.Abs.Real -> failure x
  Syntax.Types.Abs.Var ident -> failure x

transTy :: Syntax.Types.Abs.Ty -> Result
transTy x = case x of
  Syntax.Types.Abs.Leaf base -> failure x
  Syntax.Types.Abs.Prod ty1 ty2 -> failure x
  Syntax.Types.Abs.Coprod ty1 ty2 -> failure x
  Syntax.Types.Abs.Func ty1 trarrow ty2 -> failure x
  Syntax.Types.Abs.TyLater tlater ty -> failure x
  Syntax.Types.Abs.TyBox tbox ty -> failure x
  Syntax.Types.Abs.TyVar tmu ident ty -> failure x
  Syntax.Types.Abs.TyForall tforall ident ty -> failure x
