-- Syntax of GHOPFL types defined in LBNF format
-- To be processed into a parser and lexer using BNFC

entrypoints Ty ;
comment     "#" ;

token       TForall  ('∀' | '\\''-''/') ;
token       TLater   ('▶' | '|''>') ;
token       TBox     ('█' | '['']') ;
token       TMu      ('μ' | '|''u') ;
token       TRarrow  ('→' | '-''>') ;
token       TSingle  ( '𝟙' | '{''*''}' ) ;

Single.     Ty5     ::= TSingle ;
Bool.       Ty5     ::= "bool" ;
Real.       Ty5     ::= "real" ;
Var.        Ty5     ::= Ident ;

-- TODO: naming?
Prod.       Ty4     ::= Ty4 "x" Ty5 ; 
Coprod.     Ty3     ::= Ty3 "+" Ty4 ; 
Func.       Ty2     ::= Ty2 TRarrow Ty3 ; 
TyLater.    Ty1     ::= TLater Ty2 ;
TyBox.      Ty1     ::= TBox Ty2 ;
TyVar.      Ty      ::= TMu Ident "." Ty1 ;
TyForall.   Ty      ::= TForall Ident "." Ty1 ;

coercions Ty 5 ;
